---
abstract: 'MooseX::Types provided for the modern POE'
author:
  - 'Nicholas Perez <nperez@cpan.org>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-Types
requires:
  MooseX::Types: 0.20
  MooseX::Types::Structured: 0.18
  POE: 1.269
  Test::Exception: 0.27
  Test::More: 0.94
resources:
  repository: git://github.com/nperez/pxt.git
version: 0.092670
